-- BEGIN command test cases
-- Reference: https://docs.aws.amazon.com/redshift/latest/dg/r_BEGIN.html

-- Basic BEGIN statements
BEGIN;
begin;

-- BEGIN with WORK keyword
BEGIN WORK;
begin work;

-- BEGIN with TRANSACTION keyword  
BEGIN TRANSACTION;
begin transaction;

-- START TRANSACTION (alternative syntax)
START TRANSACTION;
start transaction;

-- BEGIN with isolation levels
-- Note: All isolation levels are processed as SERIALIZABLE in Redshift
BEGIN ISOLATION LEVEL SERIALIZABLE;
BEGIN ISOLATION LEVEL READ UNCOMMITTED;
BEGIN ISOLATION LEVEL READ COMMITTED;
BEGIN ISOLATION LEVEL REPEATABLE READ;

BEGIN WORK ISOLATION LEVEL SERIALIZABLE;
BEGIN WORK ISOLATION LEVEL READ UNCOMMITTED;
BEGIN WORK ISOLATION LEVEL READ COMMITTED;
BEGIN WORK ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- START TRANSACTION with isolation levels
START TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- BEGIN with access modes
BEGIN READ WRITE;
BEGIN READ ONLY;
begin read write;
begin read only;

BEGIN WORK READ WRITE;
BEGIN WORK READ ONLY;

BEGIN TRANSACTION READ WRITE;
BEGIN TRANSACTION READ ONLY;

-- START TRANSACTION with access modes
START TRANSACTION READ WRITE;
START TRANSACTION READ ONLY;

-- BEGIN with both isolation level and access mode
BEGIN ISOLATION LEVEL SERIALIZABLE READ WRITE;
BEGIN ISOLATION LEVEL SERIALIZABLE READ ONLY;
BEGIN ISOLATION LEVEL READ UNCOMMITTED READ WRITE;
BEGIN ISOLATION LEVEL READ UNCOMMITTED READ ONLY;
BEGIN ISOLATION LEVEL READ COMMITTED READ WRITE;
BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY;
BEGIN ISOLATION LEVEL REPEATABLE READ READ WRITE;
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;

-- BEGIN WORK with both isolation level and access mode
BEGIN WORK ISOLATION LEVEL SERIALIZABLE READ WRITE;
BEGIN WORK ISOLATION LEVEL SERIALIZABLE READ ONLY;
BEGIN WORK ISOLATION LEVEL READ UNCOMMITTED READ WRITE;
BEGIN WORK ISOLATION LEVEL READ UNCOMMITTED READ ONLY;

-- BEGIN TRANSACTION with both isolation level and access mode
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE READ WRITE;
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE READ ONLY;
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED READ WRITE;
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED READ ONLY;

-- START TRANSACTION with both isolation level and access mode
START TRANSACTION ISOLATION LEVEL SERIALIZABLE READ WRITE;
START TRANSACTION ISOLATION LEVEL SERIALIZABLE READ ONLY;
START TRANSACTION ISOLATION LEVEL REPEATABLE READ READ WRITE;
START TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;

-- Example from AWS documentation
begin;
begin read write;

-- Mixed case variations
Begin;
BEGIN;
BeGiN wOrK;
Start Transaction;
START transaction ISOLATION level SERIALIZABLE;
begin TRANSACTION isolation LEVEL read COMMITTED READ only;