-- ALTER MATERIALIZED VIEW test cases for Amazon Redshift
-- Reference: https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_MATERIALIZED_VIEW.html

-- Basic AUTO REFRESH examples
ALTER MATERIALIZED VIEW tickets_mv AUTO REFRESH YES;
ALTER MATERIALIZED VIEW tickets_mv AUTO REFRESH NO;

-- With schema qualification
ALTER MATERIALIZED VIEW sales.revenue_mv AUTO REFRESH YES;
ALTER MATERIALIZED VIEW analytics.customer_summary_mv AUTO REFRESH NO;

-- ALTER DISTKEY examples
ALTER MATERIALIZED VIEW sales_mv ALTER DISTKEY customer_id;
ALTER MATERIALIZED VIEW inventory_mv ALTER DISTKEY product_id;
ALTER MATERIALIZED VIEW orders_mv ALTER DISTKEY order_date;

-- ALTER DISTSTYLE examples
ALTER MATERIALIZED VIEW customer_mv ALTER DISTSTYLE ALL;
ALTER MATERIALIZED VIEW product_mv ALTER DISTSTYLE EVEN;
ALTER MATERIALIZED VIEW transaction_mv ALTER DISTSTYLE KEY DISTKEY transaction_id;
ALTER MATERIALIZED VIEW analytics_mv ALTER DISTSTYLE AUTO;

-- ALTER SORTKEY examples
ALTER MATERIALIZED VIEW sales_mv ALTER SORTKEY (sale_date);
ALTER MATERIALIZED VIEW customer_orders_mv ALTER SORTKEY (customer_id, order_date);
ALTER MATERIALIZED VIEW inventory_mv ALTER SORTKEY (warehouse_id, product_id, stock_date);

-- COMPOUND SORTKEY examples
ALTER MATERIALIZED VIEW sales_analytics_mv ALTER COMPOUND SORTKEY (region, sale_date, product_category);
ALTER MATERIALIZED VIEW customer_behavior_mv ALTER COMPOUND SORTKEY (customer_segment, activity_date);

-- SORTKEY AUTO/NONE examples
ALTER MATERIALIZED VIEW automated_mv ALTER SORTKEY AUTO;
ALTER MATERIALIZED VIEW manual_mv ALTER SORTKEY NONE;

-- ROW LEVEL SECURITY examples
ALTER MATERIALIZED VIEW sensitive_data_mv ROW LEVEL SECURITY ON;
ALTER MATERIALIZED VIEW public_data_mv ROW LEVEL SECURITY OFF;

-- ROW LEVEL SECURITY with CONJUNCTION TYPE
ALTER MATERIALIZED VIEW employee_data_mv ROW LEVEL SECURITY ON CONJUNCTION TYPE AND;
ALTER MATERIALIZED VIEW department_data_mv ROW LEVEL SECURITY ON CONJUNCTION TYPE OR;
ALTER MATERIALIZED VIEW project_data_mv ROW LEVEL SECURITY OFF CONJUNCTION TYPE AND;

-- ROW LEVEL SECURITY FOR DATASHARES
ALTER MATERIALIZED VIEW shared_analytics_mv ROW LEVEL SECURITY ON FOR DATASHARES;
ALTER MATERIALIZED VIEW shared_reports_mv ROW LEVEL SECURITY OFF FOR DATASHARES;
ALTER MATERIALIZED VIEW shared_metrics_mv ROW LEVEL SECURITY ON CONJUNCTION TYPE AND FOR DATASHARES;
ALTER MATERIALIZED VIEW shared_insights_mv ROW LEVEL SECURITY ON CONJUNCTION TYPE OR FOR DATASHARES;

-- Complex examples with quoted identifiers
ALTER MATERIALIZED VIEW "Sales-Analytics" AUTO REFRESH YES;
ALTER MATERIALIZED VIEW "Customer Orders" ALTER DISTKEY "Customer ID";
ALTER MATERIALIZED VIEW "Product-Inventory" ALTER DISTSTYLE KEY DISTKEY "Product-Code";
ALTER MATERIALIZED VIEW "Monthly-Reports" ALTER SORTKEY ("Report-Date", "Region-Code");

-- Examples with mixed case identifiers
ALTER MATERIALIZED VIEW CustomerOrdersMV AUTO REFRESH NO;
ALTER MATERIALIZED VIEW ProductInventoryMV ALTER DISTKEY ProductID;
ALTER MATERIALIZED VIEW SalesAnalyticsMV ALTER COMPOUND SORTKEY (SaleDate, RegionCode);

-- Note: OWNER TO and RENAME TO operations for materialized views use ALTER TABLE syntax in Redshift
-- These are included for reference but would use ALTER TABLE command:
-- ALTER TABLE mv_name OWNER TO new_owner;
-- ALTER TABLE mv_name RENAME TO new_name;