-- Test cases for SET SESSION CHARACTERISTICS command
-- Reference: https://docs.aws.amazon.com/redshift/latest/dg/r_SET_SESSION_CHARACTERISTICS.html
-- Note: This command is deprecated in Amazon Redshift

-- Basic isolation level settings
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- Access mode settings (READ WRITE | READ ONLY)
SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE;
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY;

-- Deferrable mode settings
SET SESSION CHARACTERISTICS AS TRANSACTION DEFERRABLE;
SET SESSION CHARACTERISTICS AS TRANSACTION NOT DEFERRABLE;

-- Combined transaction characteristics (isolation level + access mode)
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED, READ WRITE;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY;
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY, ISOLATION LEVEL REPEATABLE READ;
SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE, ISOLATION LEVEL READ UNCOMMITTED;

-- Combined with deferrable mode
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY, DEFERRABLE;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED, READ WRITE, NOT DEFERRABLE;
SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE, DEFERRABLE, ISOLATION LEVEL REPEATABLE READ;

-- All three characteristics combined
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY, DEFERRABLE;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED, READ WRITE, NOT DEFERRABLE;
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY, ISOLATION LEVEL REPEATABLE READ, DEFERRABLE;
SET SESSION CHARACTERISTICS AS TRANSACTION NOT DEFERRABLE, READ WRITE, ISOLATION LEVEL READ UNCOMMITTED;

-- Case variations (SQL keywords are case-insensitive)
set session characteristics as transaction isolation level read committed;
Set Session Characteristics As Transaction Read Write;
SET SESSION CHARACTERISTICS as TRANSACTION isolation LEVEL serializable;
SET session CHARACTERISTICS AS transaction READ only;

-- Multiple characteristics in different orders
SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE, NOT DEFERRABLE, ISOLATION LEVEL READ COMMITTED;
SET SESSION CHARACTERISTICS AS TRANSACTION DEFERRABLE, ISOLATION LEVEL SERIALIZABLE, READ ONLY;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ, DEFERRABLE, READ WRITE;

-- Typical use cases

-- Setting up a read-only session for reporting
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY, ISOLATION LEVEL READ COMMITTED;

-- Setting up a session for ETL operations
SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE, ISOLATION LEVEL READ UNCOMMITTED;

-- Setting up a session for critical financial transactions
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

-- Setting up a session for data analysis with consistent reads
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY, ISOLATION LEVEL REPEATABLE READ;

-- PostgreSQL compatibility examples
-- (Redshift may not support all PostgreSQL features, but these are standard SQL)
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY, DEFERRABLE;

-- Edge cases with spacing
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ    COMMITTED;
SET SESSION CHARACTERISTICS AS TRANSACTION   READ   WRITE  ;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE,READ ONLY,DEFERRABLE;

-- Multiple characteristics with newlines (for readability in scripts)
SET SESSION CHARACTERISTICS AS TRANSACTION 
    ISOLATION LEVEL SERIALIZABLE,
    READ ONLY,
    DEFERRABLE;

SET SESSION CHARACTERISTICS AS TRANSACTION
    READ WRITE,
    ISOLATION LEVEL READ COMMITTED,
    NOT DEFERRABLE;

-- Comments within statements
SET SESSION CHARACTERISTICS AS TRANSACTION -- Setting transaction defaults
    ISOLATION LEVEL SERIALIZABLE, -- Highest isolation level
    READ ONLY; -- Prevent accidental writes

-- Practical application scenarios

-- 1. Before running reports on production data
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY, ISOLATION LEVEL READ COMMITTED;
-- SELECT * FROM sales_data WHERE date >= '2024-01-01';

-- 2. Before ETL processes that need to see uncommitted changes
SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE, ISOLATION LEVEL READ UNCOMMITTED;
-- INSERT INTO staging_table SELECT * FROM source_table;

-- 3. For applications requiring serializable isolation
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- BEGIN;
-- UPDATE accounts SET balance = balance - 100 WHERE account_id = 1;
-- UPDATE accounts SET balance = balance + 100 WHERE account_id = 2;
-- COMMIT;

-- Note: In Amazon Redshift, this command is deprecated.
-- The recommended approach is to use SET commands for individual settings:
-- SET default_transaction_isolation TO 'serializable';
-- SET default_transaction_read_only TO true;